version: '3.8'

services:
  backend:
    build:
      target: dev
    environment:
      NODE_ENV: development
      DEBUG: recall:*
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3001:3001"
      - "9229:9229"

  frontend:
    build:
      target: dev
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"

  worker:
    environment:
      NODE_ENV: development
      DEBUG: recall:*
    volumes:
      - ./backend:/app
      - /app/node_modules

  mailhog:
    image: mailhog/mailhog:latest
    container_name: recall-mailhog
    ports:
      - "1025:1025"
      - "8025:8025" 
    networks:
      - recall-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: recall-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@recall.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - recall-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: recall-redis-commander
    restart: unless-stopped
    environment:
      REDIS_HOSTS: local:redis:6379:0:${REDIS_PASSWORD:-redispassword}
      HTTP_USER: admin
      HTTP_PASSWORD: admin
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - recall-network

volumes:
  pgadmin_data:
    driver: local